# Generated by Django 5.1.4 on 2025-01-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('start_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basseball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('N', 'Not played')], default='W', max_length=1)),
                ('Baseball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baseball')),
            ],
        ),
    ]
