# Generated by Django 5.1.4 on 2025-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseball',
            name='Player',
            field=models.ManyToManyField(related_name='baseball', to='main_app.player'),
        ),
    ]
